name: "Build & Check Docgen"

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:

jobs:
  check-docgen:
    uses: ./.github/workflows/run-docgen.yaml
    with:
        gradle_arguments: "build"
        artifact_pattern: "build/libs/**"
